version: '3.8'
services:
  web:
    build:
      context: ./
      target: production
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      DEBUG: nodejs-docker-express:*